### ISSUE TITLE
PSinject fails - does not return an agent connection when injecting into SYSTEM process

### ISSUE THREAD

**Issue by wintermute4316** [PowerShellEmpire/Empire#68] opened 2015-10-23 20:04 UTC
Testing Empire against Windows 7 Enterprise 64-bit. The initial powershell agent works fine and I get a powershell agent running as a domain user that's a member of the local Administrators groups on this system. powerup/allchecks works fine against that agent and confirms I have local admin rights showing "Current user already has local administrative privileges". Running bypassuac works fine and reports "Not in a medium integrity process" and bypassuac_wscript reports "You are already elevated", so it seems I already have the appropriate high integrity privileges. Running ps works fine as well, however when I try to psinject into a listed process with "nt authority/system" privileges, psinject starts the job, but I never get a call back with a new agent. Same result if I psinject into another process that my user owns. I seem to have all the appropriate .NET pre-reqs in the reg entry that was listed in another thread: v2.0.x, v3.0, v3.5, v4, & v4.0.

I added code to bypassuac (Invoke-BypassUAC) to provide an additional message in the console if "whoami /groups" has a "High Mandatory Level" group permission and indeed it does. I believe this is also indicated by the asterisk prepending the username in the agents view, which it is as well. In that case, psinject (Invoke-PSInject) should have sufficient privileges to function, however when it executes against an agent, it starts the job, but nothing comes back. I've tried this with a few different test Win7 Enterprise 64-bit targets with same result.

 Any ideas?

**Comment by enigma0x3** [comment] 2015-10-23 20:28
Are you able to inject into processes owned by you?

**Comment by enigma0x3** [comment] 2015-10-23 20:35
I just confirmed that I am able to inject into a process running as SYSTEM. What .NET version do you have? Please run gci "hklm:\SOFTWARE\Microsoft\NET Framework Setup\NDP" and paste the output.

**Comment by wintermute4316** [comment] 2015-10-23 21:26
PS C:\Windows\system32> gci "hklm:\SOFTWARE\Microsoft\net framework setup\ndp"

    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\net framework setup\ndp

SKC  VC Name                           Property
---  -- ----                           --------
  1   0 CDF                            {}
23   6 v2.0.50727                     {Install, Version, Increment, SP...}
  2   5 v3.0                           {Version, CBS, Increment, Install...}
  1   5 v3.5                           {Version, CBS, Install, InstallPath...}
  2   0 v4                             {}
  1   1 v4.0                           {(default)}

**Comment by wintermute4316** [comment] 2015-10-23 21:29
Oh, on the first question, I wasn't able to psinject into a process owned by me either (the user the agent is running under), however that domain user is a member of the local administrators group of that host and shows as "High Mandatory Level" when I run "whois /groups".

**Comment by enigma0x3** [comment] 2015-10-26 11:49
Ok, let's start with the injection issue. The troubleshooting process for this can be a little complicated, so I apologize. The first thing to try is to use Invoke-PSInject by itself (outside of Empire). To do this, you will need to modify Invoke-PSInject.ps1, which resides in "empire/data/module_source/management". I recommend copying the .ps1 to your desktop or something so you aren't modifying the one Empire will load. You will also want to copy the ReflectivePick dlls from empire/data/misc to your desktop as well.

To get this working properly by itself, you need to do this:
1. Base64 encode the reflectivePick dll that you copied to your desktop (if you are testing on x64, use the x64 dll, otherwise, use the x86 dll). You can base64 encode it like this in Kali "base64 -w 0 ReflectivePick_x64_orig.dll > reflective.txt".
2. Copy the contents of "reflective.txt" and paste them into either lines 2834 or 2835 in Invoke-PSInject.ps1.
3. Save Invoke-PSInject.ps1 and copy it to your Windows machine. Load the script by typing ". .\Invoke-PSInject.ps1" 
4. Once loaded, start cmd.exe and note the PID. You will be injecting into cmd.exe in order to see what errors show up.
5. With cmd.exe running, do "Invoke-PSInject -ProcID <PID> -PoshCode "Start-Process calc.exe" -verbose. This will inject PoshCode into cmd.exe using unmanaged runspaces. If it errors out, you will see the output in the cmd.exe window.

*Note: You will probably get an error in regard to the PoshCode not being Base64 encoded. You can ignore that as it will inject anyway.

Let me know if this makes sense and if you have questions. Once you do this, let me know what results you see and the error in cmd.exe if you have one.

**Comment by enigma0x3** [comment] 2015-10-26 18:36
@wintermute4316,
We just updated the reflective dlls. Can you do a pull and try injection again? Let me know the results.

**Comment by wintermute4316** [comment] 2015-10-28 18:02
Greetings enigma0x3.  I tried with the up-to-date pull and all conditions as before and I got the same result.  psinject launches the job, but no connections come back to the listener.

So next I tried the previous longer post idea to make those modifications to Invoke-PSInject and run directly on the target x64 Windows 7 host.  I followed all instructions as listed  On the target Windows 7 host, I ran a new cmd.exe (pid 5464) and a powershell console from an elevated cmd prompt (pid 5676).  Here is the output on the powershell console and the output in the injected cmd.exe.  Note that my calc.exe is in the path and if I launch a cmd prompt (elevated  or not) and type in calc.exe, it launches calc fine.

===============
Powershell console:
===============
PS C:\Windows\system32> Invoke-PSInject -ProcID 5464 -PoshCode "Start Process calc.exe" -verbose
Exception calling "FromBase64String" with "1" argument(s): "Invalid character in a Base-64 string."
At line:56 char:93
+     $PoshCode = [System.Text.Encoding]::UNICODE.GetString([System.Convert]::FromBase64String <<<< ($PoshCode));
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

VERBOSE: PowerShell ProcessID: 5676
VERBOSE: Remote Process: 5464
VERBOSE: Got the handle for the remote process to inject in to
VERBOSE: Calling Invoke-MemoryLoadLibrary
VERBOSE: 64 Bit Injection
VERBOSE: patch index: 89888
VERBOSE: replacestart: 89888
VERBOSE: replaceend: 89932
VERBOSE: Replaced pattern with: Start Process calc.exe?
VERBOSE: Getting basic PE information from the file
VERBOSE: Allocating memory for the PE and write its headers to memory
VERBOSE: Getting detailed PE information from the headers loaded in memory
VERBOSE: StartAddress: 0x0000000002750000    EndAddress: 0x0000000002775000
VERBOSE: Copy PE sections in to memory
VERBOSE: Update memory addresses based on where the PE was actually loaded in memory
VERBOSE: Import DLL's needed by the PE we are loading
VERBOSE: Importing KERNEL32.dll
VERBOSE: Importing OLEAUT32.dll
VERBOSE: Done importing DLL imports
VERBOSE: PE being loaded in to a remote process, not adjusting memory permissions
VERBOSE: Done!

PS C:\Windows\system32>

===============
Injected cmd.exe
===============
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\>ERROR: Start-Process : This command cannot be executed due to the error: The system cannot find the file s
ERROR: pecified.
ERROR: At line:1 char:6
ERROR: + Start <<<<  Process calc.exe
ERROR:     + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
ERROR:     + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcess
ERROR:    Command
ERROR:

**Comment by enigma0x3** [comment] 2015-10-28 18:21
It looks like you command is off. It should be "Start-Process calc.exe". Can you change it and post the code? Sorry!

**Comment by wintermute4316** [comment] 2015-10-28 18:29
Ah, ok.  I made that change and it did launch calc.exe just fine.  So in my case, the modified Invoke-PSInject works in that scenario if I run it locally on the target.

**Comment by enigma0x3** [comment] 2015-10-28 18:34
What process are you trying to inject into through empire?

**Comment by wintermute4316** [comment] 2015-10-28 18:46
Any x64 SYSTEM process.  From empire I've tried several x64 SYSTEM processes to inject into (svchost, winlogon, other app specific processes) and none return a new agent running as SYSTEM.

**Comment by enigma0x3** [comment] 2015-10-28 18:50
Interesting...I can't reproduce this. Can you try the manual method on your Windows target and try to inject into a SYSTEM process that way and see if calc comes up?

**Comment by wintermute4316** [comment] 2015-10-28 18:56
On the same host as before.  When I inject into a SYSTEM process (pid 1540), I get the following powershell error.  This is running from an elevated cmd prompt running the powershell console (whoami /groups shows "High Mandatory Level" permissions).

PS C:\Windows\system32> Invoke-PSInject -ProcID 1540 -PoshCode "Start-Process calc.exe" -verbose
Exception calling "FromBase64String" with "1" argument(s): "Invalid character in a Base-64 string."
At line:56 char:93
+     $PoshCode = [System.Text.Encoding]::UNICODE.GetString([System.Convert]::FromBase64String <<<< ($PoshCode));
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

VERBOSE: PowerShell ProcessID: 4900
VERBOSE: Remote Process: 1540
Invoke-Command : Couldn't obtain the handle for process ID: 1540
At line:2852 char:23
+         Invoke-Command <<<<  -ScriptBlock $RemoteScriptBlock -ArgumentList @($PEBytes64, $PEBytes32, $FuncReturnType, $ProcId, $ProcName,$ForceASLR, $PoshCode)
    + CategoryInfo          : OperationStopped: (Couldn't obtain...rocess ID: 1540:String) [Invoke-Command], RuntimeException
    + FullyQualifiedErrorId : Couldn't obtain the handle for process ID: 1540,Microsoft.PowerShell.Commands.InvokeCommandCommand

**Comment by enigma0x3** [comment] 2015-10-28 18:59
Are you unable to inject into a normal user process in Empire?

**Comment by wintermute4316** [comment] 2015-10-28 19:03
Yes, that's working now and perhaps the latest pull update fixed that (not sure).  But I am not able to inject into a SYSTEM process.  I tried a few other SYSTEM processes using the same method above and results in the same error.

**Comment by enigma0x3** [comment] 2015-10-28 19:15
Hmmm..have you rebooted recently? I'm just shooting in the air at this point..

**Comment by wintermute4316** [comment] 2015-10-28 19:37
Yeah, many times over several days, and I've also tried this elevation to SYSTEM from Empire on several different Win7 targets with same result.  Just to go back to the original posts to restate, the reason I'm trying to get to SYSTEM is I'd like to run credential gathering modules like mimikatz which fail when running under the current user which has "High Mandatory Level" permissions (see previous post on mimikatz error I get).  I've also tried turning off AV processes on the target just to see if that what's causing the elevation to SYSTEM to fail, but no effect.  However, as I stated in an earlier post as well (see last post from 5 days ago), if I use a vanilla meterpreter payload and then run getsystem, it elevates to SYSTEM just fine.  What the getsystem module does with technique 1, something like that is what I would need in Empire to do the same here.  Not sure why my case is unique from how you're testing.  My targets are Win7 x64 Enterprise joined to a Windows domain. I'm logged in as a domain user when I run the initial powershell to establish the initial agent.  That domain user is member of the local Administrators group and I've confirmed I have "High Mandatory Level" permissions with bypassuac and manually checking whoami /groups.  I should have everything I need to elevate to a SYSTEM process and it works with getsystem in msf, however does not work when I try in Empire.

**Comment by leechristensen** [comment] 2015-10-29 04:38
Can you migrate into a SYSTEM process in meterpreter? PSInject is more closely related to Meterpreter's migration than its "getsystem" command.

**Comment by wintermute4316** [comment] 2015-10-29 13:53
Initially, no. That migrate in meterpreter will fail with an access denied until I first do a getsystem in that meterpreter session.  Reason is, on that initial meterpreter session, if I do a getuid it shows I'm running as the domain user (DOMAIN\User, not NT AUTHORITY\SYSTEM) and "whoami /groups" shows I'm running with "High Mandatory Level".  In that initial state, if I do a ps, all but a couple of processes have a blank entry for the user (another indication I'm not running with system privileges).  So, until I do the getsystem in meterpreter, I can't migrate to a SYSTEM process.  After I do the getsystem, running "whoami /groups" in that session shows I'm now at "System Mandatory Level" and I can migrate to other SYSTEM processes and I can successfully run meterpreter modules like hashdump, mimikatz, kiwi, etc..

So, as I had posited in an earlier post in this thread, it seems based on what I'm seeing in my testing that Empire needs a getsystem equivalent which would allow elevating a session running as a user that is member of the local Adminstrators groups (ie. "High Mandatory Access") to a session running as "System Mandatory Level".  PSInject, like you stated, works more like the migrate capability in meterpreter and does not perform that "getsystem" elevation of access.

**Comment by enigma0x3** [comment] 2015-10-29 14:03
One thing to note, you don't need SYSTEM to run mimikatz. You can run it in an elevated context when a local administrator. If you are elevated, a * will be next to the UserName in the agents window.

I just tested this and here is my result:
<img width="1146" alt="screen shot 2015-10-29 at 10 01 32 am" src="https://cloud.githubusercontent.com/assets/6264733/10820552/2bbe38fe-7e24-11e5-8660-a9ce187e4fb2.png">

**Comment by wintermute4316** [comment] 2015-10-29 14:29
In my case, if I run the credentials/mimikatz/logonpasswords module for example, with the session running as the domain user (exactly as you have it in your screenshot pre-psinject), the module fails with the error "ERROR kuhl_m_sekurlsa_acquireLSA ; Handle on memory (0x00000005)".  If I run the psinject exactly as you have it in the screenshot above, it displays the "Job starting..." message, but never returns a new agent.  It's possible that there are local security settings that are different between your lab environment Win7 targets and mine. Perhaps I'm running more hardened UAC settings or some other local security policy setting that is preventing psinject from automatically elevating to SYSTEM (ie. "System Mandatory Level") privileges like it does in your case.  I'll keep testing this and hopefully I or someone else reading this thread might know what the missing piece is.  Just thinking out loud, if automatic elevation was always possible in every case from "High Mandatory Level" to "System Mandatory Level", there would never have been a need for a getsystem call in meterperter.  So, I'm thinking I'm hitting a scenario here that may be more common and not just affecting my particular scenario.  I'll keep looking on my end as well.

**Comment by enigma0x3** [comment] 2015-10-29 14:36
Can you check what UAC level you are running as?

**Comment by wintermute4316** [comment] 2015-10-29 15:34
Lab Win7 target's HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System:

![uac](https://cloud.githubusercontent.com/assets/9419064/10823104/798c2e7c-7e30-11e5-9faf-3c03db2c2e7a.png)

**Comment by enigma0x3** [comment] 2015-10-30 11:12
I'll manually set those in my lab and see if it makes a difference. Do you have any security products/configurations on that box? I know it is a long shot, but I am able to inject into SYSTEM processes all day long.

**Comment by enigma0x3** [comment] 2015-10-30 16:03
Just updated the dlls used for injection. Do a pull and give this a try and let me know if it still doesn't work.

**Comment by wintermute4316** [comment] 2015-10-30 23:58
Hey enigma0x3.  Last update didn't fix it, but the good news is, I figured it out.  My lab systems are VDI's and by default in my case the local Administrators group is not granted all the Windows user rights (see this link for more info user rights in Windows - https://technet.microsoft.com/en-us/library/bb457125.aspx).  It turns out it only needs one user right assigned for the psinject to work and come back with an agent running as SYSTEM - SeDebugPrivilege.  The reason you probably haven't seen this before is because the default in Windows is to assign the local Administrators group to this user right, however in my case it's not.  You can see this in the Windows GUI by opening secpol.msc - Local Policy - User Rights Assignment - "Debug Programs" = SeDebugPrivilege. Since many megacorps run VDI's, I think it would be of value to add a check for this in psinject (or the DLL?) and always grant yourself that user right.  It turns out that as a local Administrator you can grant yourself that user right just fine, but you have to request/set it or it can't inject into a SYSTEM process.  At least that's what my testing has shown.  If I add the local Administrators group to that one user right SeDebugPrivilege, psinject works every time and comes back with a SYSTEM level agent.

Is that a check/set that can be added to psinject?  If so, I can test it.

**Comment by enigma0x3** [comment] 2015-11-01 17:12
Hey @wintermute4316,
I just set this on one of my test VMs in my lab and verified that injection fails. We are actively working to fix up the injection code so it properly sets the SeDebugPrivilege when injecting. Once we have this fixed, we will push it and I will let you know so you can test.

Thanks for reporting this!

**Comment by enigma0x3** [comment] 2015-11-02 00:19
Hey @wintermute4316,
Just to verify...the local administrator group was actually *removed* from "Debug Programs", correct? If that is the case, you can't grant the process SeDebugPrivileges because removing the user/group from "Debug Programs" strips SeDebugPrivileges from the process's access token. There is logic in the script to *ENABLE* SeDebugPrivileges if it is disabled as you can disable SeDebugPrivileges while keeping the local administrators in the "Debug Programs" policy. 

If the group was actually removed, SeDebugPrivileges isn't there for us to enable. With this configuration, only processes started/running as SYSTEM can access other SYSTEM processes. This also breaks mimikatz as it can't access lsass (even if you are a local admin). I am not aware of a way to grant yourself SeDebugPrivileges if that actual attribute is stripped from the access token. A workaround is to use the invoke_psexec module, which will shovel a SYSTEM level Empire agent back to you. Since that agent is running as SYSTEM, you can access other SYSTEM processes (such as lsass) and inject/dump creds.

While looking into this, I did experiment with "GetSystem" functionality within PowerShell. This fails as you are unable to access the token of a SYSTEM process and impersonate it. As of right now, I believe the only way around that setup is to use invoke_psexec for a SYSTEM agent.

We will keep researching this and see if there is anything that can be done to circumvent the lack of the SeDebugPrivilege attribute. I can't make any promises as I don't believe there is currently a public method available to do this. 

Thanks!

**Closed** 2015-11-02 16:43 UTC
Labels: bug
